apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dags
spec:
  storageClassName: azurefile
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 250Mi
